### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by matthewlent** [manuparra/phpDIServer#1]
Hi Manu,

I am having trouble getting any connection to the DI Server, are you just connecting to the sample URL to relay your requests?

Do you have to have this code running on the server running DI Server itself?

Is it possible I could pay you to help me get connected to an instance of DI Server, having a lot of trouble figuring out SAP's documentation

-Matt
matthew.lent@gmail.com

**Comment by manuparra** [comment]
Hello Matewww did you solve your problem.
